name: Generate CLI Documentation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
          
      - name: Generate CLI Documentation
        run: |
          # Ensure docs directory exists
          mkdir -p docs
          echo "Contents of working directory before gendoc:"
          ls -la
          go run main.go gendoc
          echo "Contents of docs directory after gendoc:"
          ls -la docs/ || echo "docs directory not found"
          
      - name: Check for changes
        id: git-check
        run: |
          # Check if docs directory exists and has content
          if [ -d "docs" ] && [ "$(ls -A docs/)" ]; then
            git add docs/
            if [[ -n "$(git status --porcelain docs/)" ]]; then
              echo "changes=true" >> $GITHUB_OUTPUT
              echo "Found documentation changes to commit"
            else
              echo "changes=false" >> $GITHUB_OUTPUT  
              echo "No documentation changes detected"
            fi
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No docs directory or no files generated"
          fi
          
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "docs: Update CLI documentation"
          git push