name: Generate CLI Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
          
      - name: Generate CLI Documentation
        run: |
          go run main.go gendoc
          
      - name: Check for changes
        id: git-check
        run: |
          if [[ -n "$(git status --porcelain docs/)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "docs: Update CLI documentation"
          git push